# Generated by Django 5.0.6 on 2024-11-07 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=60)),
                ('foto', models.TextField(blank=True, null=True)),
                ('email', models.CharField(max_length=100)),
                ('telefone', models.CharField(blank=True, max_length=60, null=True)),
                ('endereco', models.CharField(blank=True, max_length=60, null=True)),
                ('status', models.CharField(default='ativo', max_length=10)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='Permissao',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('modulo', models.CharField(max_length=60)),
                ('autorizacao', models.CharField(max_length=20)),
                ('status', models.CharField(default='ativo', max_length=10)),
            ],
            options={
                'db_table': 'permissao',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=60)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='produto/')),
                ('descricao', models.TextField(blank=True, null=True)),
                ('valorAntigo', models.FloatField(blank=True, null=True)),
                ('valor', models.FloatField(blank=True, null=True)),
                ('quantidade', models.IntegerField(blank=True, default=1, null=True)),
                ('status', models.CharField(default='ativo', max_length=10)),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'db_table': 'produto',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=60, unique=True)),
                ('status', models.CharField(default='ativo', max_length=10)),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='tpcliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=60, unique=True)),
                ('status', models.CharField(default='ativo', max_length=10)),
            ],
            options={
                'verbose_name': 'Tipo de Cliente',
                'verbose_name_plural': 'Tipos de Clientes',
                'db_table': 'tpcliente',
            },
        ),
        migrations.CreateModel(
            name='Role_permissao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('permissao_id', models.ForeignKey(db_column='permissao_id', on_delete=django.db.models.deletion.CASCADE, related_name='permissao_id_utili', to='api.permissao')),
                ('role_id', models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.CASCADE, related_name='role_id_permi', to='api.role')),
            ],
            options={
                'db_table': 'role_permissao',
            },
        ),
        migrations.CreateModel(
            name='Utilizador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=60, unique=True)),
                ('password', models.CharField(max_length=60)),
                ('role_name', models.CharField(blank=True, max_length=60, null=True)),
                ('status', models.CharField(default='ativo', max_length=10)),
                ('role_id', models.ForeignKey(db_column='role_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_id_U', to='api.role')),
            ],
            options={
                'verbose_name': 'Utilizador',
                'verbose_name_plural': 'Utilizadores',
                'db_table': 'utilizador',
            },
        ),
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data', models.DateField(null=True)),
                ('hora', models.TimeField(null=True)),
                ('acao', models.CharField(max_length=60)),
                ('ip', models.CharField(blank=True, max_length=60, null=True)),
                ('status', models.CharField(default='ativo', max_length=10)),
                ('utilizador_id', models.ForeignKey(db_column='utilizador_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='utilizador_id_H', to='api.utilizador')),
            ],
            options={
                'verbose_name': 'Historico',
                'verbose_name_plural': 'Historicos',
                'db_table': 'historico',
            },
        ),
        migrations.CreateModel(
            name='utilizador_role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(default='ativo', max_length=10)),
                ('role_id', models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.CASCADE, related_name='role_id_utili', to='api.role')),
                ('utilizador_id', models.ForeignKey(db_column='utilizador_id', on_delete=django.db.models.deletion.CASCADE, related_name='utilizador_id_role', to='api.utilizador')),
            ],
            options={
                'db_table': 'utilizador_role',
            },
        ),
    ]
