# Generated by Django 5.0.6 on 2024-12-06 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_banco_conta_local_moeda_nostro_vostro_subconta_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moeda',
            old_name='sifra',
            new_name='cifra',
        ),
    ]
