# Generated by Django 5.0.6 on 2024-12-09 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_moeda_cifra_moeda_cifrao'),
    ]

    operations = [
        migrations.AddField(
            model_name='banco',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='local',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
