# Generated by Django 5.0.6 on 2024-12-09 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_banco_descricao_alter_local_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='banco',
            name='isnostra',
            field=models.IntegerField(default=0),
        ),
    ]
