# Generated by Django 5.0.6 on 2024-12-09 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_banco_isnostra'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conta',
            old_name='nome',
            new_name='numero',
        ),
    ]
