# Generated by Django 5.0.6 on 2024-12-18 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_nome_conta_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='numero',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
