services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: django_backend
    volumes:
      - ./backend:/app
    working_dir: /app
    ports:
      - "11000:8000"
    environment:
      - DEBUG=1
      - DATABASE_NAME=reconcilia
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
    depends_on:
      - db

  admin:
    image: node:20.4
    container_name: vue_admin
    command: bash -c "npm install -g yarn && yarn install --ignore-engines && yarn serve"
    volumes:
      - ./admin:/app
      - /app/node_modules
    working_dir: /app
    ports:
      - "12000:8080"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  db:
    image: postgres:16
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=reconcilia
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      
    ports:
      - "5454:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data: