version: '3.8'

services:
  backend:
    image: python:3.12
    container_name: django_backend
    command: bash -c "pip install -r requirements.txt && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
    working_dir: /app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DATABASE_NAME=reconcilia
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
    depends_on:
      - db

  admin:
    image: node:20.4
    container_name: vue_admin
    command: bash -c "yarn install --ignore-engines && yarn serve"
    volumes:
      - ./admin:/app
    working_dir: /app
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  db:
    image: postgres:16
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=reconcilia
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data: